/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:5c8eace3-114f-4f66-ba35-b3a63cd3a927",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_RbtV1wEab",
    "aws_user_pools_web_client_id": "4t9r71281hd7djn5g7rhev4mlt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "region": "ap-northeast-1",
        "userPoolId": "ap-northeast-1_RbtV1wEab",
        "userPoolWebClientId": "4t9r71281hd7djn5g7rhev4mlt",
        "mandatorySignIn": true
    }
};


export default awsmobile;
